- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: stop mysql exporter
  ansible.builtin.systemd:
    name: mysql_exporter
    state: stopped

- name: start mysql exporter
  ansible.builtin.systemd:
    name: mysql_exporter
    state: started
    enabled: yes

- name: restart mysql exporter
  ansible.builtin.systemd:
    name: mysql_exporter
    state: restarted
