global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['IP1:9100']
        labels:
          environment: 'prod'
          instance: 'prod-server'
      - targets: ['IP2:9100']
        labels:
          environment: 'dev'
          instance: 'dev-server'
      - targets: ['DB_IP:9100']
        labels:
          environment: 'mysql'
          instance: 'mysql-db'

  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['DB_IP:9104']
        labels:
          environment: 'mysql'
          instance: 'mysql-db'

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['IP1:9121']
        labels:
          environment: 'prod'
          instance: 'prod-redis'
      - targets: ['IP2:9121']
        labels:
          environment: 'dev'
          instance: 'dev-redis'

  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: 
          - 'http://IP1:3000/'
          - 'http://IP1:8000/'
          - 'http://IP1:8080/'
        labels:
          environment: 'prod'
          instance: 'prod-app'
      - targets: 
          - 'http://IP2:3000/'
          - 'http://IP2:8000/'
          - 'http://IP2:8080/'
        labels:
          environment: 'dev'
          instance: 'dev-app'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: BLACKBOX_IP:9115
