monitoring_base_dir: /opt/monitoring

prometheus_dir: "{{ monitoring_base_dir }}"
alertmanager_dir: "{{ monitoring_base_dir }}/alertmanager"
grafana_dir: "{{ monitoring_base_dir }}/grafana"

# 서비스 도메인
monitoring_domains:
  prometheus: prometheus_practice.onthe-top.com
  grafana: grafana_practice.onthe-top.com
  alertmanager: alertmanager_practice.onthe-top.com

# Prometheus
prometheus:
  dir: "{{ prometheus_dir }}"
  config: "{{ prometheus_dir }}/prometheus.yml"
  alert_rules: "{{ prometheus_dir }}/alert-rules.yml"
  volume: prometheus_data
  container_name: prometheus
  image: prom/prometheus:latest
  port: 9090
  domain: "{{ monitoring_domains.prometheus }}"

# Alertmanager
alertmanager:
  dir: "{{ alertmanager_dir }}"
  config: "{{ alertmanager_dir }}/alertmanager.yml"
  volume: alertmanager_data
  container_name: alertmanager
  image: prom/alertmanager:latest
  port: 9093
  domain: "{{ monitoring_domains.alertmanager }}"

# Grafana
grafana:
  dir: "{{ grafana_dir }}"
  provisioning_dir: "{{ grafana_dir }}/provisioning"
  dashboards_dir: "{{ grafana_dir }}/dashboards"
  volume: grafana_data
  container_name: grafana
  image: grafana/grafana:latest
  port: 3000
  domain: "{{ monitoring_domains.grafana }}"

# Nginx
nginx:
  config_path: /etc/nginx/nginx.conf
  ports:
    - 80
    - 443

# Certbot
certbot_email: sangwoon991103@gmail.com
# MySQL
mysql:
  exporter_user: exporter
  exporter_password: W9v!8aKdP2zR
